version: "3"

tasks:
  all:
    desc: "Build everything (Solidity + WASI components)"
    cmds:
      - task: forge
      - task: wasi

  forge:
    desc: "Build Solidity contracts"
    cmds:
      - forge build

  wasi:
    desc: "Build WASI components (all or specific one)"
    vars:
      WASI_BUILD_DIR: '{{.WASI_BUILD_DIR | default ""}}'
    cmds:
      - |
        warg reset || echo "warg reset failed (warg server not started), continuing..."
        RECIPE="wasi-build"
        MAKEFILE_DIRS=$(find components/* -maxdepth 1 -name "Makefile" -o -name "makefile")

        for makefile_path in $MAKEFILE_DIRS; do
            if grep -q "^${RECIPE}:" "$makefile_path" 2>/dev/null; then
                if [ "{{.WASI_BUILD_DIR}}" == "" ] || [[ "$makefile_path" == *"{{.WASI_BUILD_DIR}}"* ]]; then
                    parent_dir=$(dirname "$makefile_path")
                    make -s -C "$parent_dir" $RECIPE
                fi
            else
                echo "Recipe '$RECIPE' not found in $makefile_path"
            fi
        done
